#!/usr/bin/env python3
"""
Simple script to manually broadcast test alerts through the alert manager.

This script directly accesses the alert manager to send test alerts,
bypassing the normal vital processing pipeline.

Usage:
    python scripts/send_test_alert.py
"""

import asyncio
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from app.modules.alerts.manager import alert_manager


async def send_test_alert(
    patient_id: str,
    roles: list[str],
    vital_type: str = "heart_rate",
    tier: str = "CRITICAL",
) -> None:
    """Send a test alert through the alert manager."""
    
    alert_payload = {
        "event": "alert",
        "alert_id": uuid.uuid4().hex,
        "tier": tier,
        "patient_id": patient_id,
        "vital_type": vital_type,
        "vitals_window": [120.0, 135.0, 150.0],  # Simulated high heart rate
        "threshold": {"min": 60.0, "max": 100.0},
        "reasons": [f"{vital_type} outside normal range for 3 consecutive samples"],
        "recipients": roles,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "context": {
            "source": "test_script",
            "note": "This is a test alert generated by send_test_alert.py"
        }
    }
    
    print(f"📤 Sending test alert to patient {patient_id}")
    print(f"   Tier: {tier}")
    print(f"   Vital Type: {vital_type}")
    print(f"   Recipients: {', '.join(roles)}")
    print(f"   Alert ID: {alert_payload['alert_id']}")
    
    await alert_manager.send_to_roles(
        patient_id=patient_id,
        roles=roles,
        payload=alert_payload
    )
    
    print("✅ Alert sent successfully!")
    print("\nNote: This alert was broadcast to any connected SSE/WebSocket clients.")
    print("If no clients are connected, the alert will not be received.")


async def main() -> None:
    """Main function to send test alerts."""
    
    print("=" * 60)
    print("🚨 Test Alert Sender")
    print("=" * 60)
    print()
    
    # Get patient ID
    patient_id = input("Enter patient ID (or press Enter for test-patient-123): ").strip()
    if not patient_id:
        patient_id = "test-patient-123"
    
    # Get roles
    print("\nAvailable roles: caregiver, doctor, nurse, dispatcher, admin")
    roles_input = input("Enter roles (comma-separated, or press Enter for 'caregiver'): ").strip()
    if not roles_input:
        roles = ["caregiver"]
    else:
        roles = [r.strip() for r in roles_input.split(",")]
    
    # Get vital type
    print("\nCommon vital types: heart_rate, blood_pressure, oxygen_saturation, temperature")
    vital_type = input("Enter vital type (or press Enter for 'heart_rate'): ").strip()
    if not vital_type:
        vital_type = "heart_rate"
    
    # Get tier
    print("\nAlert tiers: CRITICAL, WARNING, INFO")
    tier = input("Enter tier (or press Enter for 'CRITICAL'): ").strip().upper()
    if not tier:
        tier = "CRITICAL"
    
    print()
    
    # Send the alert
    await send_test_alert(
        patient_id=patient_id,
        roles=roles,
        vital_type=vital_type,
        tier=tier
    )
    
    print("\n" + "=" * 60)
    print("💡 To receive this alert, make sure you have an SSE client connected:")
    print(f"   curl -N -H 'Authorization: Bearer YOUR_TOKEN' \\")
    print(f"     'http://localhost:8000/api/v1/alerts/stream?role={roles[0]}&patient_id={patient_id}'")
    print("=" * 60)


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\n\n👋 Cancelled by user")
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
